language: node_js
services:
- docker
before_install:
- docker build -t cybercuffs/woolly:woo .
- docker run -d -p 80:8080 --name  go-helloworld cybercuffs/woolly:woo
- docker exec -it go-helloworld /bin/sh -c "cd tests; go test"
script:
- docker ps | grep -q woo
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master